language: node_js
sudo: required
env:
  - RESIDUE_VERSION=2.1.2

node_js:
  - "6"
  - "7"
  - "8"
  - "9"

matrix:
  include:
  - os: linux
  - os: linux
    before_install:
    - sudo sh -c "$(curl -fsSL https://raw.githubusercontent.com/muflihun/residue-cpp/master/install.sh $RESIDUE_VERSION)"
    - npm install residue-native@latest
  - os: osx
  - os: osx
    before_install:
    - wget https://raw.githubusercontent.com/muflihun/residue-cpp/master/install.sh
    - sudo sh install.sh $RESIDUE_VERSION
    - npm install residue-native@latest

before_script:
  - pwd
  - ls -l
  - ls -l node_modules

cache:
  directories:
    - "node_modules"
