language: node_js
sudo: required
env:
  - LIBRESIDUE_VERSION=2.1.2

node_js:
  - "7"
  - "8"
  - "9"

matrix:
  include:
  - os: linux
  - os: linux
    env:
    - RESIDUE_VERSION=$LIBRESIDUE_VERSION
    before_install:
    - sudo sh -c "$(curl -fsSL https://raw.githubusercontent.com/muflihun/residue-cpp/master/install.sh)"
    - npm install residue-native@latest
  - os: osx
  - os: osx
    env:
    - RESIDUE_VERSION=$LIBRESIDUE_VERSION
    before_install:
    - wget https://raw.githubusercontent.com/muflihun/residue-cpp/master/install.sh
    - sudo sh install.sh $RESIDUE_VERSION
    - npm install residue-native@latest

before_script:
    - sh test/start-server.sh

cache:
  directories:
    - "node_modules"
