language: node_js
sudo: required

matrix:
  include:
  - os: linux
    node_js:
    - "7"
    - "8"
    - "9"
  - os: linux
    node_js:
    - "7"
    - "8"
    - "9"
    env:
    - RESIDUE_VERSION=2.1.2
    before_install:
    - sudo sh -c "$(curl -fsSL https://raw.githubusercontent.com/muflihun/residue-cpp/master/install.sh)"
    - export LD_LIBRARY_PATH=/usr/local/lib/
    - ls -l /usr/local/lib/
    - npm install residue-native@latest
  - os: osx
    node_js:
    - "7"
    - "8"
    - "9"
  - os: osx
    node_js:
    - "7"
    - "8"
    - "9"
    env:
    - RESIDUE_VERSION=2.1.2
    before_install:
    - wget https://raw.githubusercontent.com/muflihun/residue-cpp/master/install.sh
    - sudo sh install.sh $RESIDUE_VERSION
    - ls -l /usr/local/lib/
    - export LD_LIBRARY_PATH=/usr/local/lib/
    - npm install residue-native@latest

before_script:
    - sh test/start-server.sh

cache:
  directories:
    - "node_modules"
