language: node_js
sudo: required
env:
  - RESIDUE_VERSION=2.1.2

node_js:
  - "7"
  - "8"
  - "9"

matrix:
  include:
  - os: linux
  - os: linux
    env:
    - NATIVE=true
    before_install:
    - sudo sh -c "$(curl -fsSL https://raw.githubusercontent.com/muflihun/residue-cpp/master/install.sh)"
    - export LD_LIBRARY_PATH=/usr/local/lib/
    - ls -l /usr/local/lib/
    - npm install residue-native@latest
  - os: osx
  - os: osx
    env:
    - NATIVE=true
    before_install:
    - wget https://raw.githubusercontent.com/muflihun/residue-cpp/master/install.sh
    - sudo sh install.sh $RESIDUE_VERSION
    - ls -l /usr/local/lib/
    - export LD_LIBRARY_PATH=/usr/local/lib/
    - npm install residue-native@latest

before_script:
    - sh test/start-server.sh

cache:
  directories:
    - "node_modules"
