language: node_js

node_js:
  - "7"
  - "8"

matrix:
  include:
  - os: linux
  - os: linux
    before_install:
    - npm install -g residue-native@latest
  - os: osx
  - os: osx
    before_install:
    - npm install -g residue-native@latest

cache:
  directories:
    - "node_modules"
