language: node_js

node_js:
  - "7"
  - "8"

os:
  - linux
  - linux
    before_install:
    - npm install -g residue-native
  - osx
  - osx
    before_install:
    - npm install -g residue-native

cache:
  directories:
    - "node_modules"
