language: node_js
sudo: required

node_js:
  - "7"
  - "8"
  - "9"

matrix:
  include:
  - os: linux
  - os: linux
    env:
    - RESIDUE_VERSION=2.1.2 # Do not update this version until residue-cpp/releases has downloadable version. see install.sh
    before_install:
    - wget https://raw.githubusercontent.com/zuhd-org/residue-cpp/master/install.sh
    - sudo sh install.sh $RESIDUE_VERSION
    - export LD_LIBRARY_PATH=/usr/local/lib/
    - ls -l /usr/local/lib/
    - npm install residue-native@latest
  - os: osx
  - os: osx
    env:
    - RESIDUE_VERSION=2.1.2
    before_install:
    - wget https://raw.githubusercontent.com/zuhd-org/residue-cpp/master/install.sh
    - sudo sh install.sh $RESIDUE_VERSION
    - ls -l /usr/local/lib/
    - export LD_LIBRARY_PATH=/usr/local/lib/
    - npm install residue-native@latest

before_script:
    - sh test/start-server.sh

cache:
  directories:
    - "node_modules"
