language: node_js
sudo: required

node_js:
  - "7"
  - "8"

matrix:
  include:
  - os: linux
  - os: linux
    before_install:
    - sh -c "$(curl -fsSL https://raw.githubusercontent.com/muflihun/residue-cpp/master/install.sh)"
    - npm install -g residue-native@latest
  - os: osx
  - os: osx
    before_install:
    - sh -c "$(curl -fsSL https://raw.githubusercontent.com/muflihun/residue-cpp/master/install.sh)"
    - npm install -g residue-native@latest

cache:
  directories:
    - "node_modules"
